artifacts_root: artifacts

#https://drive.google.com/file/d/1YTptQHz1YP_K4eadeRgaNaxgL29ACDuJ/view?usp=sharing
#https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
#s3://chickenbucketaws/Chicken-fecal-images.zip

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5

